# numpy - From first encounter to first dive

NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

For quick reference check Help and Documentation in IPython. For more detailed documentation, along with tutorials and other resources, refer to http://www.numpy.org.

## Dynamic Types

Applied data-driven science and computation requires a clear understanding of data storage and manipulation. The most important part of these concepts is the contrast how arrays of data are handled in the Python language itself and how NumPy improves on this.

Users of Python are often drawn-in by its ease of use, specially _dynamic typing_. Understanding how this works is an important piece of learning to analyze data efficiently and effectively with Python.


## Python Integer

As Python implementaion is written in C, therefore every Python object is a cleverly-disguised C structure containing its value and other information about it. For example, from the Python 3.4 source code, we find that the integer (long) type definition effectively looks like this (once the C macros are expanded):

```
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

A single integer in Python 3.4 actually contains four pieces:

- `ob_refcnt`, a reference count that helps Python silently handle memory allocation and deallocation
- `ob_type`, which encodes the type of the variable
- `ob_size`, which specifies the size of the following data members
- `ob_digit`, which contains the actual integer value that we expect the Python variable to represent.

Therefore, there is some overhead in storing an integer in Python as compared to an integer in a compiled language like C.

This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically but at a cost. This cost becomes especially apparent in structures that combine many of these objects.


## Python List

The standard mutable multi-element container in Python is the list. We can create a list of integers as follows:

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

Or, similarly, a list of strings:

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
type(L2[0])

str

Because of Python's dynamic typing, we can even create heterogeneous lists:

In [14]:
L3 = [True, "2", 3.14, 4]
[type(item) for item in L3]

[bool, str, float, int]

But this flexibility comes at a cost, each item in the list must contain its own _type info_, _reference count_, and other information as each item is a complete Python object. In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array. At the implementation level, the array essentially contains a single pointer to one contiguous block of data.


## Fixed-Type Arrays

Python offers several options for storing data in efficient, fixed-type data buffers. The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type. Much more useful, however, is the `ndarray` object of the NumPy package that adds efficient operations on that efficient storage of data.

## Numpy ndarray

Now that we are ready to explore NumPy array, we'll start with the standard NumPy import, under the alias np:

In [2]:
import numpy as np
np.__version__

'1.21.2'

First, we can use np.array to create arrays from Python lists:

In [15]:
# integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

NumPy is constrained to arrays with homogeneous type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [16]:
np.array([3.14, 4, 2, 5])

array([3.14, 4.  , 2.  , 5.  ])

We can explicitly set the data type of the resulting array using the `dtype` keyword:

In [17]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

NumPy arrays can explicitly be multi-dimensional; here's one way:

In [18]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists are treated as rows of the resulting two-dimensional array.


### Creating Arrays from Scratch

It is more efficient to create arrays from scratch using NumPy routines. For example:


In [19]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 float array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.40316508, 0.72388978, 0.09038095],
       [0.15722965, 0.58993146, 0.3326047 ],
       [0.57541777, 0.56598508, 0.8449689 ]])

In [27]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.02952653, -0.15122883,  0.97156465],
       [ 0.57978076,  1.96468109,  0.41828246],
       [ 1.2318533 , -1.08903048,  0.18741253]])

In [28]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 1, 7],
       [6, 2, 3],
       [7, 2, 2]])

In [29]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### NumPy Array Attributes

Some useful array attributes are the size, shape, memory consumption, and data types of arrays. We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [31]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [32]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the `dtype`, the data type of the array.

In [33]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include `itemsize`, which lists the size (in bytes) of each array element, and `nbytes`, which lists the total size (in bytes) of the array:

In [34]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that `nbytes` is equal to `itemsize` times `size`.


### Array Indexing: Accessing Single Elements

In a one-dimensional array, the ith value (counting from zero) can be accessed by specifying the desired index in square brackets

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [36]:
x1[0]

5

In [37]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [38]:
x1[-1]

9

In [39]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [76]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [41]:
x2[0, 0]

3

In [42]:
x2[2, 0]

1

In [43]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [77]:
x2[0, 0] = 12
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. 

In [78]:
x1[0] = 3.14
print(x1)

[3 0 3 3 7 9]


### Array Slicing: Accessing Subarrays

We can also use square brackets them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

```
x[start:stop:step]
```

If any of these are unspecified, they default to the values `start=0`, `stop= size of dimension`, `step=1`. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

#### One-dimensional subarrays

In [79]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [80]:
print(x[:5])  # first five elements

[0 1 2 3 4]


In [81]:
print(x[5:])  # elements after index 5

[5 6 7 8 9]


In [82]:
print(x[4:7])  # middle sub-array

[4 5 6]


In [83]:
print(x[::2])  # every other element

[0 2 4 6 8]


In [84]:
print(x[1::2]) # every other element, starting at index 1

[1 3 5 7 9]


A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [85]:
print(x[::-1])  # all elements, reversed

[9 8 7 6 5 4 3 2 1 0]


In [86]:
print(x[5::-2])  # reversed every other from index 5

[5 3 1]


#### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

In [57]:
print(x2)

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [58]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [60]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [62]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [63]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [64]:
print(x2[2, :])  # last row of x2

[1 6 7 7]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [71]:
print(x2[0]) # eqivalent to x2[0,:]

[12  5  2  4]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they, unlike Python lists, return views rather than copies of the array data. 

In [70]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2×2$ subarray from this:

In [69]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [73]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [75]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [87]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [88]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [89]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays, flexibly done with the `reshape` method. For example, if you want to put the numbers 1 through 9 in a $3×3$ grid, you can do the following:

In [90]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the `reshape` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the `reshape` method, or more easily done by making use of the `newaxis` keyword within a slice operation:

In [91]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [92]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [93]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [94]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`. `np.concatenate` takes a tuple or list of arrays as its first argument, as we can see here:

In [95]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])